# Generated by Django 5.1 on 2024-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="location",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
